- name: Install python dependancies
  apt:
    name: {{ item }}
    state: present
    force: yes
    with_items:
      - python
      - python-setuptools
      - python-dev
      - build-essentials
      - python-pip
      - python-mysqldb
