-
  name: create user
  hosts: all
  tasks:
    - name: adding user
      shell:
        echo "hello there"
        echo "multiple lines"
      register: out

    - debug: msg="{{ out.stdout }}"
    - debug: msg="{{ out.stderr }}"
